### ISSUE TITLE
Passport v2 support maybe?

### ISSUE THREAD

**Issue by Shonetow** [ipunkt/laravel-oauth-introspection#1]
Hi,
Great work, but can't use it because it depends on Laravel Passport v1+ and I have v2. Is there any chance to see some updates soon?

Thanks.

**Comment by rokde** [comment]
Hi @Shonetow,

thank you. I think I can add it soon, maybe next week. Or do you want to make a pull request?

Thanks,

Robert

**Comment by Evertt** [comment]
How about v3? O:-)

**Comment by rokde** [comment]
Try version 1.0.0
