### ISSUE TITLE
uuid as a client_id

### ISSUE THREAD

**Issue by Cellard** [ipunkt/laravel-oauth-introspection#14]
Since Laravel Passport supports UUID as a client_id the controller shouldn't `intval()` it.

**Comment by rokde** [comment]
can you make a PR? we do not work with Passport at the moment.

**Comment by Cellard** [comment]
I will

But at first I would like to upgrade this package to modern version of Laravel. But it is blocked by your laravel-package-manager dependency. We need to upgrade it first.

I'm afraid of touching code I don't understand. May you upgrade laravel-package-manager yourself?

**Comment by rokde** [comment]
laravel-package-manager was updated to meet requirements.
