### ISSUE TITLE
Error whilst installing, using Laravel 5.6

### ISSUE THREAD

**Issue by ryanhalley** [ipunkt/laravel-oauth-introspection#4]
Hi! I'm getting errors during composer install - is it a simple fix to support Passport v6?

`
λ composer require ipunkt/laravel-oauth-introspection
Using version ^1.0 for ipunkt/laravel-oauth-introspection
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install ipunkt/laravel-oauth-introspection 1.0.1
    - Conclusion: remove laravel/passport v6.0.2
    - Installation request for ipunkt/laravel-oauth-introspection ^1.0 -> satisfiable by ipunkt/laravel-oauth-introspection[1.0.0, 1.0.1].
    - Conclusion: don't install laravel/passport v6.0.2
    - ipunkt/laravel-oauth-introspection 1.0.0 requires laravel/passport ~1.0|~2.0|~3.0|~4.0 -> satisfiable by laravel/passport[1.0.x-dev, 2.0.x-dev, 3.0.x-dev, 4.0.x-dev].
    - Can only install one of: laravel/passport[1.0.x-dev, v6.0.2].
    - Can only install one of: laravel/passport[2.0.x-dev, v6.0.2].
    - Can only install one of: laravel/passport[3.0.x-dev, v6.0.2].
    - Can only install one of: laravel/passport[4.0.x-dev, v6.0.2].
    - Installation request for laravel/passport (locked at v6.0.2, required as ^6.0) -> satisfiable by laravel/passport[v6.0.2].
`

**Comment by ryanhalley** [comment]
I just saw the pull request to resolve this - can it be merged?

**Comment by justb81** [comment]
@ryanhalley published a new release 1.0.2 that should resolve this issue. could you verify this?

**Comment by ryanhalley** [comment]
@justb81 Installed fine - many thanks!
